Transform: 
  AWS::Serverless-2016-10-31

Resources:
  XGBoostArpaPredictorFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: !Ref MemSizeForLambda
      Runtime: python3.12
      Timeout: 15
      Handler: lambda_xgb_arpa.lambda_handler
      CodeUri: src 
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Events:
        XGBoostApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /predict/xgb_arpa

  XGBoostBaselinePredictorFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: !Ref MemSizeForLambda
      Runtime: python3.12
      Timeout: 15
      Handler: lambda_xgb_baseline.lambda_handler
      CodeUri: src 
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Events:
        XGBoostApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /predict/xgb_baseline

  LightGBMPredictorFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: !Ref MemSizeForLambda
      Runtime: python3.12
      Timeout: 15
      Handler: lambda_lgbm.lambda_handler
      CodeUri: src
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Events:
        LgbmApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /predict/lgbm

Parameters:
  MemSizeForLambda:
    Description: Memory size for lambda functions
    Type: Number
    Default: 512
    AllowedValues:
      - 256
      - 512
      - 1024    